project:
  type: book
  output-dir: docs

book:
  title: "A Tour of Machine Learning Tools"
  author: "Dan MacLean"
  date: "May 2022"
  search: true
  downloads: [pdf]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 03-unsupervised.qmd
    - 04-supervised.qmd
    - 05-deep_learning.qmd
  appendices:
    - prerequisites.qmd
    - r-fundamentals.qmd

bibliography: book.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
comments:
  hypothesis: true
