--- 
title: "A Tour of Machine Learning Tools"
author: "Dan MacLean"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "A tour of selected machine learning tools that are used in plant pathogenomics research"
---

# Setting up

The primary purpose of this course is to help you to understand how to use statistical tools for machine Learning that will help with your research. The course will try to introduce you to the capabilities and limitations of some widely used machine learning tools, without leaning heavily on the maths or computer science of these things too much. By the end we hope that you'll have a decent appreciation of what machine learning can do for you, though we don't expect that you'll become expert in any way.

We'll be making use of the R statistical programming environment to do that side of the work. The rest of this chapter will help you get that set up on your own computer.

## Prerequisites

### Knowledge prerequisites

There are no specific knowledge prerequisites for this book but it will be very helpful if you have read and worked through the `Data Driven Visualisation`, `Data Exploration`, `Intro to Stats`, `Estimation Statistics` and `Bayesian Inference`  books and are familiar with R use.


### Software prerequisites

You need to install the following stuff for this book: 

 1. R
 2. RStudio
 3. Some R packages: `tidyverse`, `factoextra`, `patchwork`
 

## Installing R

Follow this link and install the right version for your operating system [https://www.stats.bris.ac.uk/R/](https://www.stats.bris.ac.uk/R/)

## Installing RStudio

Follow this link and install the right version for your operating system [https://www.rstudio.com/products/rstudio/download/](https://www.rstudio.com/products/rstudio/download/)

## Installing R packages in RStudio

### Standard packages

In the RStudio console, type

`install.packages(c("tidyverse","factoextra", "patchwork", "ggdendro", "class", "caret", "e1071","randomForest", "neuralnet"))`


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'tidyverse', 'factoextra','patchwork'
), 'packages.bib')
```
